### ISSUE TITLE
Web scraping the catalog

### ISSUE THREAD

**Issue by JoeCleveland** [apython1998/ClassPlanner#45]
Done when: Scrap the catalog and add to master course schedule. Demo by adding option to list all courses in the directory.

**Comment by apython1998** [comment]
Get prereqs and the semester that a course is offered

**Comment by apython1998** [comment]
Course follows structure of course in exTranscriptEntry.json

Prerequisite classes are held in prereqs
ORs kept in chooseOnes

**Comment by apython1998** [comment]
3.5 hours in

**Comment by apython1998** [comment]
5.5 Hours in 

Writing to file, still working on algorithm to parse prereqs

**Comment by apython1998** [comment]
6.25 Hours total

wrote to file, prereqs as good as they're going to get right now, will add card to fix them and make them perfect at a later date
