### ISSUE TITLE
Web scraping majors

### ISSUE THREAD

**Issue by dshane8** [apython1998/ClassPlanner#46]
Done when we have a JSON file that represents all majors the class planner will evaluate for

Demo by printing out all of the majors

**Comment by apython1998** [comment]
Get the courses that are required for a major: https://catalog.ithaca.edu/undergrad/programsaz/undergraduate-degree/

**Comment by apython1998** [comment]
2.5 Hrs in, gets major title, type, and finds the table with requirements. 

TODO: Get the individual requirements and choose one

**Comment by apython1998** [comment]
4.5 Hrs in, get major title, type, single course requirements

TODO: chooseOne and Select x of the following not included rn

**Comment by apython1998** [comment]
5.5 Hrs, major catalog now holds the actual course objects

**Comment by apython1998** [comment]
6.5 Hrs, Total, major catalog is loaded on system startup and students can add their major at time of registration
